#!/bin/tcsh
#PBS -l walltime=04:00:00
#PBS -N FakeNews
#PBS -l nodes=1:hail:ppn=1
#PBS -l mem=8gb
#PBS -j oe
#PBS -m aef

cd $PBS_O_WORKDIR
module load anaconda3/4.4.0

time -f "%E %M %K" python3 bayesclassify.py
